services:
  - type: web
    name: tg-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/bot.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
    healthCheckPath: /health
